# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import log_pb2 as proto_dot_log__pb2


class LogControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SaveLog = channel.unary_unary(
                '/log.LogController/SaveLog',
                request_serializer=proto_dot_log__pb2.UserData.SerializeToString,
                response_deserializer=proto_dot_log__pb2.ReturnMessage.FromString,
                )


class LogControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SaveLog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LogControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SaveLog': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveLog,
                    request_deserializer=proto_dot_log__pb2.UserData.FromString,
                    response_serializer=proto_dot_log__pb2.ReturnMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'log.LogController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LogController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SaveLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/log.LogController/SaveLog',
            proto_dot_log__pb2.UserData.SerializeToString,
            proto_dot_log__pb2.ReturnMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
